apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-replicaset
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongo-init
          image: mongo:latest
          command:
            [
              "bash",
              "-c",
              "
              echo 'Waiting for MongoDB pods...';
              for pod in mongo-0 mongo-1 mongo-2; do
                until ping -c1 $pod.mongo-headless.default.svc.cluster.local &>/dev/null; do
                  echo Waiting for $pod...;
                  sleep 2;
                done;
              done;
              sleep 10;
              echo 'Initiating ReplicaSet...';
              mongo --host mongo-0.mongo-headless.default.svc.cluster.local:27017 --eval '
                rs.initiate({
                  _id: \"rs0\",
                  members: [
                    { _id: 0, host: \"mongo-0.mongo-headless.default.svc.cluster.local:27017\" },
                    { _id: 1, host: \"mongo-1.mongo-headless.default.svc.cluster.local:27017\" },
                    { _id: 2, host: \"mongo-2.mongo-headless.default.svc.cluster.local:27017\" }
                  ]
                })
              ';
              "
            ]