apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tracing
spec:
  serviceName: "tracing-headless"
  replicas: 1
  selector:
    matchLabels:
      app: tracing
  template:
    metadata:
      labels:
        app: tracing
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.52
          ports:
            - containerPort: 16686
            - containerPort: 14268