apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nomadstatefulworkloads.nomad.hashicorp.com
spec:
  group: nomad.hashicorp.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                resources:
                  type: object
                  properties:
                    cpu:
                      type: integer
                    memory:
                      type: integer
                update:
                  type: object
                  properties:
                    maxParallel:
                      type: integer
                    healthCheck:
                      type: string
                scaling:
                  type: object
                  properties:
                    minReplicas:
                      type: integer
                    maxReplicas:
                      type: integer
                    metrics:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          resource:
                            type: object
                            properties:
                              name:
                                type: string
                              target:
                                type: object
                                properties:
                                  type:
                                    type: string
                                  averageUtilization:
                                    type: integer
                affinity:
                  type: object
                  properties:
                    nodeAffinity:
                      type: object
                      properties:
                        requiredDuringSchedulingIgnoredDuringExecution:
                          type: object
                          properties:
                            nodeSelectorTerms:
                              type: array
                              items:
                                type: object
                                properties:
                                  matchExpressions:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        key:
                                          type: string
                                        operator:
                                          type: string
                                        values:
                                          type: array
                                          items:
                                            type: string
            status:
              type: object
              properties:
                jobStatus:
                  type: string
                versions:
                  type: array
                  items:
                    type: object
                    properties:
                      nomadJobSpec:
                        type: object
  scope: Namespaced
  names:
    plural: nomadstatefulworkloads
    singular: nomadstatefulworkload
    kind: NomadStatefulWorkload
    shortNames:
      - nsw
