---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nomad-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nomad-controller-role
rules:
  - apiGroups: ["nomad.hashicorp.com"]
    resources: ["nomadstatefulworkloads"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nomad-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nomad-controller-role
subjects:
  - kind: ServiceAccount
    name: nomad-controller
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomad-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nomad-controller
  template:
    metadata:
      labels:
        app: nomad-controller
    spec:
      serviceAccountName: nomad-controller
      containers:
        - name: controller
          image: your-registry/nomad-controller:latest
          imagePullPolicy: Always
          env:
            - name: NOMAD_ADDR
              value: "http://nomad-server.default.svc.cluster.local:4646" # Заменить при необходимости
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
