# nomad-controller-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nomad-controller-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nomad-controller-role
rules:
- apiGroups: ["nomad.hashicorp.com"]
  resources: ["nomadstatefulworkloads"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nomad-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nomad-controller-role
subjects:
- kind: ServiceAccount
  name: nomad-controller-sa
  namespace: default