apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nomadstatefulworkloads.nomad.hashicorp.com
spec:
  group: nomad.hashicorp.com
  names:
    kind: NomadStatefulWorkload
    listKind: NomadStatefulWorkloadList
    plural: nomadstatefulworkloads
    singular: nomadstatefulworkload
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
                resources:
                  type: object
                  properties:
                    cpu:
                      type: integer
                      minimum: 100
                      maximum: 8000
                    memory:
                      type: integer
                      minimum: 128
                      maximum: 32768
                  required: [cpu, memory]
                affinity:
                  type: object
                  properties:
                    nodeAffinity:
                      type: object
                      properties:
                        requiredDuringSchedulingIgnoredDuringExecution:
                          type: object
                          properties:
                            nodeSelectorTerms:
                              type: array
                              items:
                                type: object
                                properties:
                                  matchExpressions:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        key:
                                          type: string
                                        operator:
                                          type: string
                                          enum: [In, NotIn, Exists, DoesNotExist]
                                        values:
                                          type: array
                                          items:
                                            type: string
                task:
                  type: object
                  properties:
                    name:
                      type: string
                    driver:
                      type: string
                    config:
                      type: object
                      additionalProperties: true
                  required: [name, driver]
              required: [replicas, resources, task]
      additionalPrinterColumns:
        - name: Replicas
          type: integer
          jsonPath: .spec.replicas
        - name: CPU
          type: integer
          jsonPath: .spec.resources.cpu
        - name: Memory
          type: integer
          jsonPath: .spec.resources.memory
